///////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2000-2017 Ericsson Telecom AB
//
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v1.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v10.html
///////////////////////////////////////////////////////////////////////////////
//
//  File:               MTP3asp_EncDec.cc
//  Rev:                R12A
//  Prodnr:             CNL 113 337
//  Updated:            2007-09-17
//  Contact:            http://ttcn.ericsson.se
///////////////////////////////////////////////////////////////////////////////

// Please note: Because the encoder/decoder functions are generated by the 
// TITAN, the MTP3asp_EncDec.cc is kept only for compatibility issue and 
// should be removed from the projects.
